const router=require('express').Router();
const jwt=require('jsonwebtoken');
const db=require('../db');
const multer=require('multer');
const {adminAuth}=require('../middleware/auth');
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024},fileFilter:(req,file,cb)=>cb(null,/^image\/(png|jpe?g|webp|gif)$/.test(file.mimetype))});
router.post('/login',async(req,res)=>{const {email,password}=req.body;if(email===process.env.ADMIN_EMAIL&&password===process.env.ADMIN_PASSWORD){if(!process.env.JWT_SECRET)return res.status(500).json({error:'JWT_SECRET is not configured'});res.cookie('tos_admin',jwt.sign({email,role:'admin'},process.env.JWT_SECRET,{expiresIn:'2d'}),{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:2*86400000});return res.json({ok:true});}res.status(401).json({error:'Invalid admin credentials'});});
router.post('/logout',(req,res)=>{res.clearCookie('tos_admin');res.json({ok:true});});
router.get('/me',adminAuth,(req,res)=>res.json({admin:req.admin}));
router.get('/products',adminAuth,async(req,res)=>{const {rows}=await db.query('SELECT id,name,description,category,price,stock,status,delivery_text,image_url,(image_data IS NOT NULL) AS has_image FROM products ORDER BY created_at DESC');res.json({products:rows.map(p=>({...p,price:Number(p.price),image_url:p.has_image?`/api/products/${p.id}/image`:p.image_url}))});});
router.post('/products',adminAuth,upload.single('image'),async(req,res)=>{try{const {name,description,category,price,stock,delivery_text}=req.body;if(!name||!description||!category||price===''||stock==='')return res.status(400).json({error:'Ürün adı, açıklama, kategori, fiyat ve stok zorunludur.'});
  if(!['Oyun','Sosyal','Hizmet','Paket'].includes(category))return res.status(400).json({error:'Geçerli bir kategori seçmelisin.'});
  if(!Number.isFinite(Number(price))||Number(price)<0)return res.status(400).json({error:'Geçerli bir fiyat gir.'});
  if(!Number.isInteger(Number(stock))||Number(stock)<0)return res.status(400).json({error:'Stok 0 veya daha büyük bir tam sayı olmalı.'});const f=req.file;const {rows}=await db.query(`INSERT INTO products(name,description,category,price,stock,delivery_text,image_data,image_mime) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id`,[name.trim(),description.trim(),category,Number(price),Number(stock),delivery_text?.trim()||null,f?.buffer||null,f?.mimetype||null]);res.status(201).json({id:rows[0].id});}catch(e){if(e.code==='23505')return res.status(409).json({error:'A product with this name already exists'});res.status(400).json({error:e.message||'Could not save product'});}});
router.put('/products/:id',adminAuth,upload.single('image'),async(req,res)=>{try{const {name,description,category,price,stock,status,delivery_text}=req.body;if(!name||!description||!category||price===''||stock==='')return res.status(400).json({error:'Ürün adı, açıklama, kategori, fiyat ve stok zorunludur.'});if(!['Oyun','Sosyal','Hizmet','Paket'].includes(category))return res.status(400).json({error:'Geçerli bir kategori seçmelisin.'});if(!Number.isFinite(Number(price))||Number(price)<0)return res.status(400).json({error:'Geçerli bir fiyat gir.'});if(!Number.isInteger(Number(stock))||Number(stock)<0)return res.status(400).json({error:'Stok 0 veya daha büyük bir tam sayı olmalı.'});const values=[name?.trim(),description?.trim(),category,Number(price),Number(stock),status||'active',delivery_text?.trim()||null];let sql='UPDATE products SET name=$1,description=$2,category=$3,price=$4,stock=$5,status=$6,delivery_text=$7,updated_at=NOW()';if(req.file){values.push(req.file.buffer,req.file.mimetype);sql+=`,image_data=$${values.length-1},image_mime=$${values.length}`;}sql+=` WHERE id=$${values.length+1}`;values.push(req.params.id);await db.query(sql,values);res.json({ok:true});}catch(e){res.status(400).json({error:e.message||'Could not update product'});}});
router.delete('/products/:id',adminAuth,async(req,res)=>{await db.query("UPDATE products SET status='inactive',updated_at=NOW() WHERE id=$1",[req.params.id]);res.json({ok:true});});
router.get('/orders',adminAuth,async(req,res)=>{const {rows}=await db.query(`SELECT o.*,cp.expected_amount,cp.received_amount,cp.tx_hash,cp.status AS crypto_status,COALESCE((SELECT json_agg(json_build_object('name',oi.product_name,'quantity',oi.quantity,'unit_price',oi.unit_price) ORDER BY oi.id) FROM order_items oi WHERE oi.order_id=o.id),'[]'::json) AS items FROM orders o LEFT JOIN crypto_payments cp ON cp.order_id=o.id ORDER BY o.created_at DESC`);res.json({orders:rows});});
router.patch('/orders/:id',adminAuth,async(req,res)=>{const allowed=['pending','paid','processing','completed','cancelled'];if(!allowed.includes(req.body.status))return res.status(400).json({error:'Invalid status'});await db.query('UPDATE orders SET status=$1 WHERE id=$2',[req.body.status,req.params.id]);res.json({ok:true});});
router.get('/messages',adminAuth,async(req,res)=>{const {rows}=await db.query('SELECT * FROM messages ORDER BY created_at DESC');res.json({messages:rows});});
router.get('/payment-notifications',adminAuth,async(req,res)=>{const {rows}=await db.query(`SELECT pn.*,o.total,o.status AS order_status,cp.expected_amount,cp.tx_hash AS confirmed_tx FROM payment_notifications pn JOIN orders o ON o.id=pn.order_id LEFT JOIN crypto_payments cp ON cp.order_id=o.id ORDER BY pn.created_at DESC LIMIT 100`);res.json({notifications:rows});});
router.patch('/payment-notifications/:id',adminAuth,async(req,res)=>{const allowed=['new','reviewed','matched'];if(!allowed.includes(req.body.status))return res.status(400).json({error:'Invalid notification status'});await db.query('UPDATE payment_notifications SET status=$1 WHERE id=$2',[req.body.status,req.params.id]);res.json({ok:true});});
router.get('/reviews',adminAuth,async(req,res)=>{const {rows}=await db.query(`SELECT r.*,p.name AS product_name,u.nickname FROM reviews r JOIN products p ON p.id=r.product_id JOIN users u ON u.id=r.user_id ORDER BY r.created_at DESC LIMIT 200`);res.json({reviews:rows});});
router.delete('/reviews/:id',adminAuth,async(req,res)=>{await db.query('DELETE FROM reviews WHERE id=$1',[req.params.id]);res.json({ok:true});});


router.get('/users',adminAuth,async(req,res)=>{const q=String(req.query.q||'').trim().toLowerCase();const vals=[];let where='';if(q){vals.push('%'+q+'%');where='WHERE LOWER(u.nickname) LIKE $1 OR LOWER(u.email) LIKE $1 OR LOWER(u.display_name) LIKE $1';}const {rows}=await db.query(`SELECT u.id,u.nickname,u.email,u.display_name,u.bio,u.account_status,u.last_seen_at,u.moderation_note,u.email_verified,u.created_at,(u.avatar_data IS NOT NULL) has_avatar,(u.cover_data IS NOT NULL) has_cover,COALESCE(up.profile_public,TRUE) profile_public FROM users u LEFT JOIN user_preferences up ON up.user_id=u.id ${where} ORDER BY u.created_at DESC LIMIT 250`,vals);res.json({users:rows.map(u=>({...u,online:!!u.last_seen_at && (Date.now()-new Date(u.last_seen_at).getTime())<5*60*1000,avatar_url:u.has_avatar?`/api/users/avatar/${u.id}`:null,cover_url:u.has_cover?`/api/users/cover/${u.id}`:null}))});});
router.patch('/users/:id',adminAuth,async(req,res)=>{try{const displayName=String(req.body.display_name||'').trim().slice(0,60);const bio=String(req.body.bio||'').trim().slice(0,500);const allowed=['active','suspended','banned'];const status=allowed.includes(req.body.account_status)?req.body.account_status:'active';const profilePublic=req.body.profile_public!==false;const note=String(req.body.moderation_note||'').trim().slice(0,500);await db.query("UPDATE users SET display_name=COALESCE(NULLIF($1,''),nickname),bio=$2,account_status=$3,moderation_note=$4,updated_at=NOW() WHERE id=$5",[displayName,bio,status,note,req.params.id]);await db.query('INSERT INTO user_preferences(user_id,profile_public) VALUES($1,$2) ON CONFLICT(user_id) DO UPDATE SET profile_public=EXCLUDED.profile_public,updated_at=NOW()',[req.params.id,profilePublic]);res.json({ok:true});}catch(e){res.status(400).json({error:e.message||'Kullanıcı güncellenemedi.'});}});
router.delete('/users/:id/avatar',adminAuth,async(req,res)=>{await db.query('UPDATE users SET avatar_data=NULL,avatar_mime=NULL,updated_at=NOW() WHERE id=$1',[req.params.id]);res.json({ok:true});});
router.delete('/users/:id/cover',adminAuth,async(req,res)=>{await db.query('UPDATE users SET cover_data=NULL,cover_mime=NULL,updated_at=NOW() WHERE id=$1',[req.params.id]);res.json({ok:true});});

router.post('/maintenance/purge-demo',adminAuth,async(req,res)=>{const client=await db.connect();try{await client.query('BEGIN');await client.query('DELETE FROM payment_notifications');await client.query('DELETE FROM crypto_payments');await client.query('DELETE FROM order_items');await client.query('DELETE FROM orders');await client.query('DELETE FROM messages');await client.query('DELETE FROM reviews');await client.query('COMMIT');res.json({ok:true})}catch(e){await client.query('ROLLBACK');console.error('purge-demo:',e.message);res.status(500).json({error:'Deneme kayıtları temizlenemedi.'})}finally{client.release()}});

module.exports=router;
