const router=require('express').Router();
const jwt=require('jsonwebtoken');
const db=require('../db');
const multer=require('multer');
const {adminAuth}=require('../middleware/auth');
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024},fileFilter:(req,file,cb)=>cb(null,/^image\/(png|jpe?g|webp|gif)$/.test(file.mimetype))});
router.post('/login',async(req,res)=>{const {email,password}=req.body;if(email===process.env.ADMIN_EMAIL&&password===process.env.ADMIN_PASSWORD){if(!process.env.JWT_SECRET)return res.status(500).json({error:'JWT_SECRET is not configured'});res.cookie('tos_admin',jwt.sign({email,role:'admin'},process.env.JWT_SECRET,{expiresIn:'2d'}),{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:2*86400000});return res.json({ok:true});}res.status(401).json({error:'Invalid admin credentials'});});
router.post('/logout',(req,res)=>{res.clearCookie('tos_admin');res.json({ok:true});});
router.get('/me',adminAuth,(req,res)=>res.json({admin:req.admin}));
router.get('/products',adminAuth,async(req,res)=>{try{const {rows}=await db.query(`SELECT p.id,p.name,p.description,p.category,p.price,p.stock,p.external_platform,p.external_url,p.status,p.delivery_text,p.instant_delivery,p.delivery_time_text,p.image_url,(p.image_data IS NOT NULL) AS has_image,p.created_at,p.updated_at,COALESCE((SELECT SUM(oi.quantity) FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE oi.product_id=p.id AND o.status IN ('paid','processing','completed')),0) AS sold_count FROM products p ORDER BY p.created_at DESC`);res.json({products:rows.map(p=>({...p,price:Number(p.price),image_url:p.has_image?`/api/products/${p.id}/image`:p.image_url}))});}catch(e){console.error('admin products list:',e.message);res.status(500).json({error:'Ürünler yüklenemedi.'});}});
function validateProduct(body){const name=String(body.name||'').trim();const description=String(body.description||'').trim();const category=String(body.category||'').trim();const price=Number(body.price);const stock=Number(body.stock);const allowed=['Oyun','Sosyal','Instagram','TikTok','Telegram','Twitter','Facebook','Snapchat','Discord','PSN','Steam','Twitch','Hizmet','Paket'];if(!name||!description||!category)return 'Ürün adı, açıklama ve kategori zorunludur.';if(!allowed.includes(category))return 'Geçerli bir kategori seçmelisin.';if(!Number.isFinite(price)||price<0)return 'Geçerli bir fiyat gir.';if(!Number.isInteger(stock)||stock<0)return 'Stok 0 veya daha büyük bir tam sayı olmalı.';const ext=String(body.external_url||'').trim();if(ext&&(!/^https?:\/\//i.test(ext)||ext.length>500))return 'Bağlantı adresi geçersiz veya çok uzun.';return null;}
router.post('/products',adminAuth,upload.single('image'),async(req,res)=>{try{const err=validateProduct(req.body);if(err)return res.status(400).json({error:err});const {name,description,category,price,stock,delivery_text,instant_delivery,delivery_time_text,external_platform,external_url}=req.body;const f=req.file;const {rows}=await db.query(`INSERT INTO products(name,description,category,price,stock,delivery_text,instant_delivery,delivery_time_text,external_platform,external_url,image_data,image_mime,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,'active') RETURNING id`,[name,description,category,Number(price),Number(stock),String(delivery_text||'').trim()||null,Boolean(instant_delivery==='true'||instant_delivery===true),String(delivery_time_text||'').trim().slice(0,80)||null,String(external_platform||'').trim()||null,String(external_url||'').trim()||null,f?.buffer||null,f?.mimetype||null]);res.status(201).json({ok:true,id:rows[0].id});}catch(e){if(e.code==='23505')return res.status(409).json({error:'Aynı isimde bir ürün zaten var. Ürün adını değiştir.'});console.error('admin product create:',e);res.status(500).json({error:'Ürün kaydedilemedi.'});}});
router.put('/products/:id',adminAuth,upload.single('image'),async(req,res)=>{try{const id=Number(req.params.id);if(!Number.isInteger(id)||id<1)return res.status(400).json({error:'Geçersiz ürün ID.'});const err=validateProduct(req.body);if(err)return res.status(400).json({error:err});const status=['active','inactive'].includes(req.body.status)?req.body.status:'active';const vals=[String(req.body.name).trim(),String(req.body.description).trim(),String(req.body.category).trim(),Number(req.body.price),Number(req.body.stock),status,String(req.body.delivery_text||'').trim()||null,Boolean(req.body.instant_delivery==='true'||req.body.instant_delivery===true),String(req.body.delivery_time_text||'').trim().slice(0,80)||null,String(req.body.external_platform||'').trim()||null,String(req.body.external_url||'').trim()||null];let sql='UPDATE products SET name=$1,description=$2,category=$3,price=$4,stock=$5,status=$6,delivery_text=$7,instant_delivery=$8,delivery_time_text=$9,external_platform=$10,external_url=$11,updated_at=NOW()';if(req.file){vals.push(req.file.buffer,req.file.mimetype);sql+=`,image_data=$${vals.length-1},image_mime=$${vals.length}`;}sql+=` WHERE id=$${vals.length+1} RETURNING id`;vals.push(id);const {rows}=await db.query(sql,vals);if(!rows[0])return res.status(404).json({error:'Ürün bulunamadı.'});res.json({ok:true,id});}catch(e){if(e.code==='23505')return res.status(409).json({error:'Aynı isimde bir ürün zaten var.'});console.error('admin product update:',e);res.status(500).json({error:'Ürün güncellenemedi.'});}});
router.patch('/products/:id/status',adminAuth,async(req,res)=>{const id=Number(req.params.id);const status=req.body?.status;if(!Number.isInteger(id)||!['active','inactive'].includes(status))return res.status(400).json({error:'Geçersiz ürün durumu.'});const {rows}=await db.query('UPDATE products SET status=$1,updated_at=NOW() WHERE id=$2 RETURNING id,status',[status,id]);if(!rows[0])return res.status(404).json({error:'Ürün bulunamadı.'});res.json({ok:true,status:rows[0].status});});
router.delete('/products/:id/image',adminAuth,async(req,res)=>{const id=Number(req.params.id);const {rowCount}=await db.query('UPDATE products SET image_data=NULL,image_mime=NULL,updated_at=NOW() WHERE id=$1',[id]);if(!rowCount)return res.status(404).json({error:'Ürün bulunamadı.'});res.json({ok:true});});
router.post('/products/:id/duplicate',adminAuth,async(req,res)=>{const id=Number(req.params.id);const {rows:src}=await db.query('SELECT * FROM products WHERE id=$1',[id]);if(!src[0])return res.status(404).json({error:'Ürün bulunamadı.'});let name=`${src[0].name} (Kopya)`;let n=2;while(true){const {rows:x}=await db.query('SELECT 1 FROM products WHERE name=$1',[name]);if(!x[0])break;name=`${src[0].name} (Kopya ${n++})`;}const {rows}=await db.query(`INSERT INTO products(name,description,category,price,stock,delivery_text,instant_delivery,delivery_time_text,external_platform,external_url,image_data,image_mime,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,'inactive') RETURNING id`,[name,src[0].description,src[0].category,src[0].price,src[0].stock,src[0].delivery_text,src[0].instant_delivery,src[0].delivery_time_text,src[0].external_platform,src[0].external_url,src[0].image_data,src[0].image_mime]);res.status(201).json({ok:true,id:rows[0].id});});
router.delete('/products/:id',adminAuth,async(req,res)=>{
  const id=Number(req.params.id);
  if(!Number.isInteger(id)||id<1)return res.status(400).json({error:'Geçersiz ürün ID.'});
  const client=await db.connect();
  try{
    await client.query('BEGIN');
    const {rows:product}=await client.query('SELECT id,name FROM products WHERE id=$1 FOR UPDATE',[id]);
    if(!product[0]){await client.query('ROLLBACK');return res.status(404).json({error:'Ürün bulunamadı.'});}

    // Satış geçmişini koru: order_items içindeki ürün adı/fiyatı snapshot olarak kalır.
    // product_id yalnızca canlı katalog ürününe referanstır ve NULL olabilir.
    await client.query('UPDATE order_items SET product_id=NULL WHERE product_id=$1',[id]);
    // Ürün yorumları ürün kataloğuna aittir; ürün silinirken kaldırılır.
    await client.query('DELETE FROM reviews WHERE product_id=$1',[id]);

    const {rows:deleted}=await client.query('DELETE FROM products WHERE id=$1 RETURNING id,name',[id]);
    if(!deleted[0])throw new Error('Ürün silinemedi.');
    await client.query('COMMIT');
    return res.json({ok:true,deleted:true,id:deleted[0].id,name:deleted[0].name,message:'Ürün kalıcı olarak silindi. Satış geçmişi korundu.'});
  }catch(e){
    await client.query('ROLLBACK').catch(()=>{});
    console.error('admin product delete:',e);
    return res.status(500).json({error:e.code==='23502'?'Satış geçmişi bağlantısı güncellenemedi. Veritabanı migrationı uygulanmamış.':`Ürün silinemedi: ${e.message||'veritabanı hatası'}`});
  }finally{client.release();}
});

router.get('/orders',adminAuth,async(req,res)=>{const {rows}=await db.query(`SELECT o.*,cp.expected_amount,cp.received_amount,cp.tx_hash,cp.status AS crypto_status,COALESCE((SELECT json_agg(json_build_object('name',oi.product_name,'quantity',oi.quantity,'unit_price',oi.unit_price) ORDER BY oi.id) FROM order_items oi WHERE oi.order_id=o.id),'[]'::json) AS items FROM orders o LEFT JOIN crypto_payments cp ON cp.order_id=o.id ORDER BY o.created_at DESC`);res.json({orders:rows});});
router.patch('/orders/:id',adminAuth,async(req,res)=>{const allowed=['pending','paid','processing','completed','cancelled'];if(!allowed.includes(req.body.status))return res.status(400).json({error:'Invalid status'});await db.query('UPDATE orders SET status=$1 WHERE id=$2',[req.body.status,req.params.id]);res.json({ok:true});});
router.get('/messages',adminAuth,async(req,res)=>{const {rows}=await db.query('SELECT * FROM messages ORDER BY created_at DESC');res.json({messages:rows});});
router.get('/payment-notifications',adminAuth,async(req,res)=>{const {rows}=await db.query(`SELECT pn.*,o.total,o.status AS order_status,cp.expected_amount,cp.tx_hash AS confirmed_tx FROM payment_notifications pn JOIN orders o ON o.id=pn.order_id LEFT JOIN crypto_payments cp ON cp.order_id=o.id ORDER BY pn.created_at DESC LIMIT 100`);res.json({notifications:rows});});
router.patch('/payment-notifications/:id',adminAuth,async(req,res)=>{const allowed=['new','reviewed','matched'];if(!allowed.includes(req.body.status))return res.status(400).json({error:'Invalid notification status'});await db.query('UPDATE payment_notifications SET status=$1 WHERE id=$2',[req.body.status,req.params.id]);res.json({ok:true});});
router.get('/reviews',adminAuth,async(req,res)=>{const {rows}=await db.query(`SELECT r.*,p.name AS product_name,u.nickname FROM reviews r JOIN products p ON p.id=r.product_id JOIN users u ON u.id=r.user_id ORDER BY r.created_at DESC LIMIT 200`);res.json({reviews:rows});});
router.delete('/reviews/:id',adminAuth,async(req,res)=>{await db.query('DELETE FROM reviews WHERE id=$1',[req.params.id]);res.json({ok:true});});


router.get('/users',adminAuth,async(req,res)=>{const q=String(req.query.q||'').trim().toLowerCase();const vals=[];let where='';if(q){vals.push('%'+q+'%');where='WHERE LOWER(u.nickname) LIKE $1 OR LOWER(u.email) LIKE $1 OR LOWER(u.display_name) LIKE $1';}const {rows}=await db.query(`SELECT u.id,u.nickname,u.email,u.display_name,u.bio,u.account_status,u.last_seen_at,u.moderation_note,u.email_verified,u.created_at,(u.avatar_data IS NOT NULL) has_avatar,(u.cover_data IS NOT NULL) has_cover,COALESCE(up.profile_public,TRUE) profile_public FROM users u LEFT JOIN user_preferences up ON up.user_id=u.id ${where} ORDER BY u.created_at DESC LIMIT 250`,vals);res.json({users:rows.map(u=>({...u,online:!!u.last_seen_at && (Date.now()-new Date(u.last_seen_at).getTime())<5*60*1000,avatar_url:u.has_avatar?`/api/users/avatar/${u.id}`:null,cover_url:u.has_cover?`/api/users/cover/${u.id}`:null}))});});
router.patch('/users/:id',adminAuth,async(req,res)=>{try{const displayName=String(req.body.display_name||'').trim().slice(0,60);const bio=String(req.body.bio||'').trim().slice(0,500);const allowed=['active','suspended','banned'];const status=allowed.includes(req.body.account_status)?req.body.account_status:'active';const profilePublic=req.body.profile_public!==false;const note=String(req.body.moderation_note||'').trim().slice(0,500);await db.query("UPDATE users SET display_name=COALESCE(NULLIF($1,''),nickname),bio=$2,account_status=$3,moderation_note=$4,updated_at=NOW() WHERE id=$5",[displayName,bio,status,note,req.params.id]);await db.query('INSERT INTO user_preferences(user_id,profile_public) VALUES($1,$2) ON CONFLICT(user_id) DO UPDATE SET profile_public=EXCLUDED.profile_public,updated_at=NOW()',[req.params.id,profilePublic]);res.json({ok:true});}catch(e){res.status(400).json({error:e.message||'Kullanıcı güncellenemedi.'});}});
router.delete('/users/:id/avatar',adminAuth,async(req,res)=>{await db.query('UPDATE users SET avatar_data=NULL,avatar_mime=NULL,updated_at=NOW() WHERE id=$1',[req.params.id]);res.json({ok:true});});
router.delete('/users/:id/cover',adminAuth,async(req,res)=>{await db.query('UPDATE users SET cover_data=NULL,cover_mime=NULL,updated_at=NOW() WHERE id=$1',[req.params.id]);res.json({ok:true});});


module.exports=router;
