const router=require('express').Router();
const db=require('../db');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');const multer=require('multer');const {userAuth}=require('../middleware/user');
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:2*1024*1024},fileFilter:(req,file,cb)=>cb(null,/^image\/(png|jpe?g|webp)$/.test(file.mimetype))});
function cookie(res,token){res.cookie('tos_user',token,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:30*86400000});}
router.post('/register',async(req,res)=>{try{const nickname=String(req.body.nickname||'').trim();const password=String(req.body.password||'');if(!/^[a-zA-Z0-9_]{3,24}$/.test(nickname))return res.status(400).json({error:'Nickname 3-24 karakter olmalı; harf, sayı ve _ kullanılabilir.'});if(password.length<8)return res.status(400).json({error:'Şifre en az 8 karakter olmalı.'});const hash=await bcrypt.hash(password,12);const {rows}=await db.query('INSERT INTO users(nickname,password_hash,display_name) VALUES($1,$2,$1) RETURNING id,nickname,display_name',[nickname.toLowerCase(),hash,nickname]);const token=jwt.sign({id:rows[0].id},process.env.JWT_SECRET,{expiresIn:'30d'});cookie(res,token);res.status(201).json({user:rows[0]});}catch(e){res.status(e.code==='23505'?409:400).json({error:e.code==='23505'?'Bu nickname zaten alınmış.':e.message});}});
router.post('/login',async(req,res)=>{const nickname=String(req.body.nickname||'').trim().toLowerCase(),password=String(req.body.password||'');const {rows}=await db.query('SELECT * FROM users WHERE nickname=$1',[nickname]);if(!rows[0]||!(await bcrypt.compare(password,rows[0].password_hash)))return res.status(401).json({error:'Nickname veya şifre hatalı.'});const token=jwt.sign({id:rows[0].id},process.env.JWT_SECRET,{expiresIn:'30d'});cookie(res,token);res.json({user:{id:rows[0].id,nickname:rows[0].nickname,display_name:rows[0].display_name}});});
router.post('/logout',(req,res)=>{res.clearCookie('tos_user');res.json({ok:true});});
router.get('/me',userAuth,async(req,res)=>res.json({user:{...req.user,avatar_url:req.user.avatar_mime?`/api/users/avatar/${req.user.id}`:null}}));
router.get('/profile/:nickname',async(req,res)=>{const {rows}=await db.query('SELECT id,nickname,display_name,bio,created_at,(avatar_data IS NOT NULL) has_avatar FROM users WHERE nickname=$1',[String(req.params.nickname).toLowerCase()]);if(!rows[0])return res.status(404).json({error:'Profil bulunamadı.'});res.json({profile:{...rows[0],avatar_url:rows[0].has_avatar?`/api/users/avatar/${rows[0].id}`:null}});});
router.get('/avatar/:id',async(req,res)=>{const {rows}=await db.query('SELECT avatar_data,avatar_mime FROM users WHERE id=$1',[req.params.id]);if(!rows[0]?.avatar_data)return res.status(404).end();res.type(rows[0].avatar_mime||'image/png');res.set('Cache-Control','public,max-age=3600');res.send(rows[0].avatar_data);});
router.put('/profile',userAuth,upload.single('avatar'),async(req,res)=>{const displayName=String(req.body.display_name||'').trim().slice(0,60),bio=String(req.body.bio||'').trim().slice(0,500);let sql='UPDATE users SET display_name=$1,bio=$2,updated_at=NOW()';const values=[displayName||req.user.nickname,bio];if(req.file){values.push(req.file.buffer,req.file.mimetype);sql+=`,avatar_data=$3,avatar_mime=$4`;}sql+=' WHERE id=$'+(values.length+1);values.push(req.user.id);await db.query(sql,values);res.json({ok:true});});
module.exports=router;
