const express=require('express');const cookieParser=require('cookie-parser');const path=require('path');const dotenv=require('dotenv');const http=require('http');const jwt=require('jsonwebtoken');const {WebSocketServer}=require('ws');dotenv.config();const db=require('./db');
const app=express();
const BUILD_VERSION='9.1.0-private-rooms';app.set('trust proxy',1);app.use(express.json({limit:'3mb'}));app.use(express.urlencoded({extended:true}));app.use(cookieParser());
app.use('/assets',express.static(path.join(__dirname,'..','assets')));app.use(express.static(path.join(__dirname,'..')));
app.use('/api/products',require('./routes/products'));app.use('/api/orders',require('./routes/orders'));app.use('/api/crypto',require('./routes/crypto').router);app.use('/api/payments',require('./routes/payments'));app.use('/api/messages',require('./routes/messages'));const calls=require('./routes/calls');app.use('/api/calls',calls.router);app.use('/api/admin',require('./routes/admin'));app.use('/api/users',require('./routes/users'));app.use('/api/reviews',require('./routes/reviews'));app.use('/api/settings',require('./routes/settings'));app.use('/api/assistant',require('./routes/assistant'));
const ADMIN_PATH=String(process.env.ADMIN_PATH||'control-room-7x91').replace(/^\/+|\/+$/g,'');app.get('/'+ADMIN_PATH,(req,res)=>res.sendFile(path.join(__dirname,'private-admin.html')));app.get('/admin',(req,res)=>res.status(404).send('Not found'));app.get('/'+ADMIN_PATH+'/',(req,res)=>res.sendFile(path.join(__dirname,'private-admin.html')));
app.get('/health',(req,res)=>res.json({ok:true,service:'tos-market',build:BUILD_VERSION,payment:'TRX/TRON'}));
app.get('/api/version',(req,res)=>res.json({build:BUILD_VERSION,payment:'TRX/TRON',wallet:process.env.TRX_PAYMENT_ADDRESS||''}));
const port=Number(process.env.PORT||3000);
const server=http.createServer(app);const wss=new WebSocketServer({server,path:'/ws/calls'});
function parseCookies(h=''){const out={};h.split(';').forEach(x=>{const i=x.indexOf('=');if(i>0)out[x.slice(0,i).trim()]=decodeURIComponent(x.slice(i+1).trim())});return out;}
async function wsUser(req){try{const token=parseCookies(req.headers.cookie||'').tos_user;if(!token||!process.env.JWT_SECRET)return null;const p=jwt.verify(token,process.env.JWT_SECRET);const {rows}=await db.query("SELECT u.id,u.nickname,u.display_name FROM users u LEFT JOIN user_preferences p ON p.user_id=u.id WHERE u.id=$1 AND u.account_status='active' AND COALESCE(p.profile_public,TRUE)=TRUE",[p.id]);return rows[0]||null;}catch{return null;}}
function send(ws,msg){if(ws.readyState===1)ws.send(JSON.stringify(msg));}
wss.on('connection',async(ws,req)=>{const user=await wsUser(req);if(!user){send(ws,{type:'error',error:'Giriş yapmış ve profili açık bir hesap gerekli.'});return ws.close(1008,'auth');}const url=new URL(req.url,'http://localhost');const roomId=String(url.searchParams.get('room')||'').toUpperCase();const room=calls.rooms.get(roomId);if(!room){send(ws,{type:'error',error:'Görüşme odası bulunamadı.'});return ws.close(1008,'room');}if(room.members.size>=5){send(ws,{type:'error',error:'Bu oda 5 kişi sınırına ulaştı.'});return ws.close(1008,'full');}
const peerId=String(user.id);const existing=[...room.members.values()].map(x=>({peerId:x.peerId,user:x.user}));room.members.set(peerId,{ws,peerId,user});send(ws,{type:'joined',room:calls.roomInfo(room),self:{peerId,user},peers:existing});for(const m of room.members.values()){if(m.peerId!==peerId)send(m.ws,{type:'peer-joined',peerId,user});}
ws.on('message',raw=>{try{const m=JSON.parse(String(raw));if(['offer','answer','ice','chat'].includes(m.type)){const target=room.members.get(String(m.to));if(target)send(target.ws,{...m,from:peerId,user});}}catch{}});
ws.on('close',()=>{room.members.delete(peerId);for(const m of room.members.values())send(m.ws,{type:'peer-left',peerId});if(room.members.size===0&&room.owner_id!==user.id)calls.rooms.delete(room.id);});
});
(async()=>{try{await db.initDb();server.listen(port,'0.0.0.0',()=>console.log(`TOS MARKET running on ${port}`));}catch(err){console.error('Database initialization failed:',err);process.exit(1);}})();
