const express=require('express');
const cookieParser=require('cookie-parser');
const path=require('path');
const dotenv=require('dotenv');
const db=require('./db');
dotenv.config();
const app=express();
app.set('trust proxy',1);
app.use(express.json({limit:'2mb'}));
app.use(express.urlencoded({extended:true}));
app.use(cookieParser());
app.use('/assets',express.static(path.join(__dirname,'..','assets')));
app.use(express.static(path.join(__dirname,'..')));
app.use('/api/products',require('./routes/products'));
app.use('/api/orders',require('./routes/orders'));
app.use('/api/messages',require('./routes/messages'));
app.use('/api/admin',require('./routes/admin'));
app.get('/admin',(req,res)=>res.sendFile(path.join(__dirname,'..','admin','index.html')));
app.get('/health',(req,res)=>res.json({ok:true}));
const port=Number(process.env.PORT||3000);
(async()=>{try{await db.initDb();app.listen(port,'0.0.0.0',()=>console.log(`TOS MARKET running on ${port}`));}catch(err){console.error('Database initialization failed:',err);process.exit(1);}})();
