const CART_KEY='tos_market_cart_v4';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:0}).format(Number(n||0));
function cart(){try{return JSON.parse(localStorage.getItem(CART_KEY)||'[]')}catch{return[]}}
function saveCart(c){localStorage.setItem(CART_KEY,JSON.stringify(c));updateCount()}
function updateCount(){const el=$('#cartCount');if(el)el.textContent=cart().reduce((s,x)=>s+x.quantity,0)}
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.remove('hidden');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.add('hidden'),2800)}
async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{...(opt.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(opt.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'Bir hata oluştu');return d}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function addToCart(p){if(Number(p.stock)<=0)return toast('Bu ürün şu anda stokta yok.');const c=cart(),i=c.find(x=>x.productId===p.id);if(i)i.quantity=Math.min(i.quantity+1,Number(p.stock));else c.push({productId:p.id,name:p.name,price:Number(p.price),stock:Number(p.stock),image_url:p.image_url,quantity:1});saveCart(c);toast('Ürün sepete eklendi')}
function productCard(p){const img=p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.name)}">`:`<div class="placeholder">${esc((p.category||'T').slice(0,1))}</div>`;return `<article class="product"><a class="product-img" href="/product.html?id=${p.id}">${img}<span class="product-badge">${esc(p.category)}</span></a><div class="product-body"><a href="/product.html?id=${p.id}"><h3>${esc(p.name)}</h3></a><p>${esc(p.description)}</p><div class="product-foot"><div><div class="price">${money(p.price)}</div><div class="stock">${Number(p.stock)>0?`${p.stock} adet mevcut`:'Stokta yok'}</div></div><button class="btn btn-primary" ${Number(p.stock)<=0?'disabled':''} onclick='event.preventDefault();addToCart(${JSON.stringify(p).replace(/'/g,"&#39;")})'>${Number(p.stock)>0?'Sepete ekle':'Tükendi'}</button></div></div></article>`}
async function loadProducts(category='Tümü',q=''){const box=$('#products');if(!box)return;box.innerHTML='<div class="loading-state">Ürünler yükleniyor...</div>';try{const params={category:category==='Tümü'?'All':category,q};const d=await api('/api/products?'+new URLSearchParams(params));box.innerHTML=d.products.length?d.products.map(productCard).join(''):'<div class="empty">Bu filtrede henüz ürün yok.</div>'}catch(e){box.innerHTML='<div class="empty">Marketplace verileri yüklenemedi.</div>'}}
function initHome(){updateCount();const params=new URLSearchParams(location.search);let cat=params.get('category')||'Tümü';$$('[data-cat]').forEach(b=>{b.classList.toggle('active',b.dataset.cat===cat);b.onclick=()=>{cat=b.dataset.cat;$$('[data-cat]').forEach(x=>x.classList.remove('active'));b.classList.add('active');loadProducts(cat,$('#search')?.value.trim()||'')}});const search=$('#search');if(search){let timer;search.oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>loadProducts(cat,search.value.trim()),180)}}loadProducts(cat,search?.value||'')}
function renderCart(){const box=$('#cartItems'),sum=$('#cartTotal'),count=$('#cartLineCount');if(!box)return;const c=cart();if(count)count.textContent=c.reduce((s,x)=>s+x.quantity,0);if(!c.length){box.innerHTML='<div class="empty" style="min-height:260px">Sepetin şu an boş.<br><br><a class="btn btn-primary" href="/#market">Marketplace\'e git</a></div>';if(sum)sum.textContent=money(0);return}box.innerHTML=c.map((x,i)=>`<div class="cart-row"><div class="cart-info">${x.image_url?`<img src="${esc(x.image_url)}" alt="">`:'<div class="mini-placeholder">T</div>'}<div><strong>${esc(x.name)}</strong><div class="muted">${money(x.price)} / adet</div></div></div><div class="qty"><button onclick="changeQty(${i},-1)">−</button><span>${x.quantity}</span><button onclick="changeQty(${i},1)">+</button></div><div class="line-total"><strong>${money(x.price*x.quantity)}</strong><button class="link-danger" onclick="removeItem(${i})">Kaldır</button></div></div>`).join('');const total=c.reduce((s,x)=>s+x.price*x.quantity,0);if(sum)sum.textContent=money(total);const subtotal=$('#cartSubtotal');if(subtotal)subtotal.textContent=money(total)}
function changeQty(i,d){const c=cart();if(!c[i])return;c[i].quantity=Math.max(1,Math.min(c[i].quantity+d,c[i].stock));saveCart(c);renderCart()}function removeItem(i){const c=cart();c.splice(i,1);saveCart(c);renderCart()}
async function initProduct(){const box=$('#productDetail');if(!box)return;const id=new URLSearchParams(location.search).get('id');if(!id)return box.innerHTML='<div class="empty">Ürün bulunamadı.</div>';try{const d=await api('/api/products/'+encodeURIComponent(id)),p=d.product;document.title=`${p.name} — TOS MARKET`;box.innerHTML=`<div class="detail-media">${p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.name)}">`:`<div class="detail-placeholder">${esc((p.category||'T').slice(0,1))}</div>`}</div><div class="detail-copy"><div class="kicker">${esc(p.category)} / TOS MARKET</div><h1>${esc(p.name)}</h1><p>${esc(p.description)}</p><div class="detail-price">${money(p.price)}</div><div class="muted">${p.stock>0?`${p.stock} adet mevcut`:'Stokta yok'}</div><button class="btn btn-primary btn-large" ${p.stock<=0?'disabled':''} onclick='addToCart(${JSON.stringify(p).replace(/'/g,"&#39;")})'>${p.stock>0?'Sepete ekle ↗':'Stokta yok'}</button></div>`}catch(e){box.innerHTML='<div class="empty">Ürün bulunamadı.</div>'}}
function initCheckout(){const form=$('#checkoutForm');if(!form)return;const c=cart();if(!c.length){location.href='/cart.html';return}const total=c.reduce((s,x)=>s+x.price*x.quantity,0);if($('#checkoutTotal'))$('#checkoutTotal').textContent=money(total);form.onsubmit=async e=>{e.preventDefault();const fd=new FormData(form),items=c.map(x=>({productId:x.productId,quantity:x.quantity})),btn=form.querySelector('button[type=submit]');btn.disabled=true;try{const d=await api('/api/orders',{method:'POST',body:JSON.stringify({name:fd.get('name'),email:fd.get('email'),note:fd.get('note'),items})});localStorage.removeItem(CART_KEY);updateCount();$('#checkoutResult').classList.remove('hidden');$('#orderNumber').textContent='#'+d.orderId;$('#mailAddress').textContent=d.adminEmail;const subject=encodeURIComponent('TOS MARKET Sipariş #'+d.orderId);const body=encodeURIComponent(`Merhaba, TOS MARKET siparişim #${d.orderId} için kripto ödeme bilgilerini rica ediyorum.\n\nToplam: ${money(d.total)}`);$('#emailOrder').href='mailto:'+d.adminEmail+'?subject='+subject+'&body='+body;form.classList.add('hidden');toast('Sipariş oluşturuldu')}catch(err){toast(err.message);btn.disabled=false}}}
function initContact(){const f=$('#contactForm');if(!f)return;f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f);try{const d=await api('/api/messages',{method:'POST',body:JSON.stringify(Object.fromEntries(fd.entries()))});$('#contactResult').textContent=d.sent?'Mesajın ekibimize ve e-posta kutumuza iletildi.':'Mesajın kaydedildi. E-posta servisi yapılandırıldığında bildirim de iletilir.';$('#contactResult').classList.remove('hidden');f.reset();toast('Mesaj gönderildi')}catch(err){toast(err.message)}}}
updateCount();document.addEventListener('DOMContentLoaded',()=>{initHome();renderCart();initProduct();initCheckout();initContact()});window.changeQty=changeQty;window.removeItem=removeItem;window.addToCart=addToCart;
