const router=require('express').Router();
const db=require('../db');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');const multer=require('multer');const {userAuth}=require('../middleware/user');
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:2*1024*1024},fileFilter:(req,file,cb)=>cb(null,/^image\/(png|jpe?g|webp)$/.test(file.mimetype))});
const coverUpload=multer({storage:multer.memoryStorage(),limits:{fileSize:15*1024*1024},fileFilter:(req,file,cb)=>cb(null,/^(image\/(png|jpe?g|webp|gif)|video\/(mp4|webm))$/.test(file.mimetype))});
function cookie(res,token){res.cookie('tos_user',token,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:30*86400000});}
function normalizeEmail(v){return String(v||'').trim().toLowerCase();}
function validEmail(v){return /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/i.test(v);}
const SOCIALS=['instagram','youtube','facebook','discord','tiktok','twitter','snapchat','telegram'];
function safeSocialUrl(v){try{const u=new URL(String(v||'').trim());return ['http:','https:'].includes(u.protocol)?u.toString().slice(0,500):''}catch{return ''}}
function socialLabel(p){return ({instagram:'Instagram',youtube:'YouTube',facebook:'Facebook',discord:'Discord',tiktok:'TikTok',twitter:'Twitter / X',snapchat:'Snapchat',telegram:'Telegram'})[p]||p;}
function userSafe(row){return {id:row.id,nickname:row.nickname,email:row.email||'',display_name:row.display_name};}
router.post('/register',async(req,res)=>{try{
  const nickname=String(req.body.nickname||'').trim();
  const email=normalizeEmail(req.body.email);
  const password=String(req.body.password||'');
  const confirm=String(req.body.confirm_password||'');
  if(!/^[a-zA-Z0-9_]{3,24}$/.test(nickname))return res.status(400).json({error:'Nickname 3-24 karakter olmalı; sadece harf, sayı ve _ kullanılabilir.'});
  if(!validEmail(email)||email.length>255)return res.status(400).json({error:'Geçerli bir e-posta adresi gir.'});
  if(password.length<8||password.length>72)return res.status(400).json({error:'Şifre 8-72 karakter arasında olmalı.'});
  if(confirm&&password!==confirm)return res.status(400).json({error:'Şifreler eşleşmiyor.'});
  const existing=await db.query('SELECT nickname,email FROM users WHERE LOWER(nickname)=LOWER($1) OR LOWER(email)=LOWER($2) LIMIT 1',[nickname,email]);
  if(existing.rows[0])return res.status(409).json({error:existing.rows[0].nickname.toLowerCase()===nickname.toLowerCase()?'Bu nickname zaten alınmış.':'Bu e-posta zaten kayıtlı.'});
  const hash=await bcrypt.hash(password,12);
  const {rows}=await db.query('INSERT INTO users(nickname,email,password_hash,display_name) VALUES($1,$2,$3,$1) RETURNING id,nickname,email,display_name',[nickname.toLowerCase(),email,hash]);
  await db.query('INSERT INTO user_preferences(user_id) VALUES($1) ON CONFLICT DO NOTHING',[rows[0].id]);const token=jwt.sign({id:rows[0].id},process.env.JWT_SECRET,{expiresIn:'30d'});cookie(res,token);res.status(201).json({user:userSafe(rows[0])});
}catch(e){console.error('register:',e.message);res.status(e.code==='23505'?409:400).json({error:e.code==='23505'?'Nickname veya e-posta zaten kayıtlı.':'Kayıt işlemi başarısız.'});}});
router.post('/login',async(req,res)=>{try{
  const identifier=String(req.body.identifier||req.body.nickname||req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');
  if(!identifier||!password)return res.status(400).json({error:'E-posta/nickname ve şifre gerekli.'});
  const {rows}=await db.query('SELECT * FROM users WHERE LOWER(nickname)=LOWER($1) OR LOWER(email)=LOWER($1) LIMIT 1',[identifier]);
  if(!rows[0]||!(await bcrypt.compare(password,rows[0].password_hash)))return res.status(401).json({error:'E-posta/nickname veya şifre hatalı.'});
  const token=jwt.sign({id:rows[0].id},process.env.JWT_SECRET,{expiresIn:'30d'});cookie(res,token);res.json({user:userSafe(rows[0])});
}catch(e){console.error('login:',e.message);res.status(500).json({error:'Giriş işlemi başarısız.'});}});
router.post('/logout',(req,res)=>{res.clearCookie('tos_user');res.json({ok:true});});
router.get('/me',userAuth,async(req,res)=>{const pref=await db.query('SELECT profile_public FROM user_preferences WHERE user_id=$1',[req.user.id]);if(!pref.rows[0])await db.query('INSERT INTO user_preferences(user_id) VALUES($1) ON CONFLICT DO NOTHING',[req.user.id]);const socials=await db.query('SELECT platform,url FROM user_socials WHERE user_id=$1 ORDER BY platform',[req.user.id]);res.json({user:{...req.user,avatar_url:req.user.avatar_mime?`/api/users/avatar/${req.user.id}`:null,cover_url:req.user.cover_mime?`/api/users/cover/${req.user.id}`:null,profile_public:pref.rows[0]?.profile_public!==false,socials:socials.rows}})});
router.get('/profile/:nickname',async(req,res)=>{const {rows}=await db.query("SELECT id,nickname,display_name,bio,created_at,(avatar_data IS NOT NULL) has_avatar,(cover_data IS NOT NULL) has_cover FROM users WHERE nickname=$1 AND account_status='active'",[String(req.params.nickname).toLowerCase()]);if(!rows[0])return res.status(404).json({error:'Profil bulunamadı.'});const pref=await db.query('SELECT profile_public FROM user_preferences WHERE user_id=$1',[rows[0].id]);if(pref.rows[0]?.profile_public===false)return res.status(404).json({error:'Profil gizli.'});const socials=await db.query('SELECT platform,url FROM user_socials WHERE user_id=$1 ORDER BY platform',[rows[0].id]);res.json({profile:{...rows[0],avatar_url:rows[0].has_avatar?`/api/users/avatar/${rows[0].id}`:null,cover_url:rows[0].has_cover?`/api/users/cover/${rows[0].id}`:null,socials:socials.rows}});});
router.get('/id/:id',async(req,res)=>{const {rows}=await db.query("SELECT id,nickname,display_name,bio,created_at,(avatar_data IS NOT NULL) has_avatar,(cover_data IS NOT NULL) has_cover FROM users WHERE id=$1 AND account_status='active'",[req.params.id]);if(!rows[0])return res.status(404).json({error:'Profil bulunamadı.'});const pref=await db.query('SELECT profile_public FROM user_preferences WHERE user_id=$1',[rows[0].id]);if(pref.rows[0]?.profile_public===false)return res.status(404).json({error:'Profil gizli.'});const socials=await db.query('SELECT platform,url FROM user_socials WHERE user_id=$1 ORDER BY platform',[rows[0].id]);res.json({profile:{...rows[0],avatar_url:rows[0].has_avatar?`/api/users/avatar/${rows[0].id}`:null,cover_url:rows[0].has_cover?`/api/users/cover/${rows[0].id}`:null,socials:socials.rows}});});
router.get('/cover/:id',async(req,res)=>{const {rows}=await db.query('SELECT cover_data,cover_mime FROM users WHERE id=$1',[req.params.id]);if(!rows[0]?.cover_data)return res.status(404).end();res.type(rows[0].cover_mime||'image/jpeg');res.set('Cache-Control','public,max-age=3600');res.send(rows[0].cover_data);});
router.delete('/cover',userAuth,async(req,res)=>{await db.query('UPDATE users SET cover_data=NULL,cover_mime=NULL,updated_at=NOW() WHERE id=$1',[req.user.id]);res.json({ok:true});});
router.post('/cover',userAuth,coverUpload.single('cover'),async(req,res)=>{if(!req.file)return res.status(400).json({error:'Geçerli bir GIF, görsel veya MP4/WebM video seç.'});await db.query('UPDATE users SET cover_data=$1,cover_mime=$2,updated_at=NOW() WHERE id=$3',[req.file.buffer,req.file.mimetype,req.user.id]);res.json({ok:true,cover_url:`/api/users/cover/${req.user.id}`});});
router.get('/avatar/:id',async(req,res)=>{const {rows}=await db.query('SELECT avatar_data,avatar_mime FROM users WHERE id=$1',[req.params.id]);if(!rows[0]?.avatar_data)return res.status(404).end();res.type(rows[0].avatar_mime||'image/png');res.set('Cache-Control','public,max-age=3600');res.send(rows[0].avatar_data);});
router.delete('/avatar',userAuth,async(req,res)=>{await db.query('UPDATE users SET avatar_data=NULL,avatar_mime=NULL,updated_at=NOW() WHERE id=$1',[req.user.id]);res.json({ok:true});});
router.put('/profile',userAuth,upload.single('avatar'),async(req,res)=>{const displayName=String(req.body.display_name||'').trim().slice(0,60),bio=String(req.body.bio||'').trim().slice(0,500);let sql='UPDATE users SET display_name=$1,bio=$2,updated_at=NOW()';const values=[displayName||req.user.nickname,bio];if(req.file){values.push(req.file.buffer,req.file.mimetype);sql+=`,avatar_data=$3,avatar_mime=$4`;}sql+=' WHERE id=$'+(values.length+1);values.push(req.user.id);await db.query(sql,values);res.json({ok:true});});

router.get('/preferences',userAuth,async(req,res)=>{await db.query('INSERT INTO user_preferences(user_id) VALUES($1) ON CONFLICT DO NOTHING',[req.user.id]);const {rows}=await db.query('SELECT profile_public FROM user_preferences WHERE user_id=$1',[req.user.id]);res.json({preferences:rows[0]||{profile_public:true}});});
router.put('/preferences',userAuth,async(req,res)=>{const profilePublic=req.body.profile_public!==false;await db.query('INSERT INTO user_preferences(user_id,profile_public) VALUES($1,$2) ON CONFLICT(user_id) DO UPDATE SET profile_public=EXCLUDED.profile_public,updated_at=NOW()',[req.user.id,profilePublic]);res.json({ok:true,profile_public:profilePublic});});
router.put('/socials',userAuth,async(req,res)=>{try{const incoming=Array.isArray(req.body?.socials)?req.body.socials:[];const allowed=new Set(SOCIALS);const clean=[];for(const item of incoming){const platform=String(item?.platform||'').toLowerCase();if(!allowed.has(platform))continue;const url=safeSocialUrl(item?.url);if(url)clean.push({platform,url});}const client=await db.connect();try{await client.query('BEGIN');await client.query('DELETE FROM user_socials WHERE user_id=$1',[req.user.id]);for(const x of clean)await client.query('INSERT INTO user_socials(user_id,platform,url) VALUES($1,$2,$3)',[req.user.id,x.platform,x.url]);await client.query('COMMIT');res.json({ok:true,socials:clean});}catch(e){await client.query('ROLLBACK');throw e}finally{client.release();}}catch(e){console.error('socials:',e.message);res.status(400).json({error:'Sosyal bağlantılar kaydedilemedi.'});}});
router.get('/socials',userAuth,async(req,res)=>{const {rows}=await db.query('SELECT platform,url FROM user_socials WHERE user_id=$1 ORDER BY platform',[req.user.id]);res.json({socials:rows});});
router.get('/public/list',async(req,res)=>{try{const q=String(req.query.q||'').trim().toLowerCase();const values=[];let where="WHERE COALESCE(up.profile_public,TRUE)=TRUE";if(q){values.push('%'+q+'%');where+=' AND (LOWER(u.nickname) LIKE $1 OR LOWER(u.display_name) LIKE $1)';}const {rows}=await db.query(`SELECT u.id,u.nickname,u.display_name,u.bio,u.created_at,(u.avatar_data IS NOT NULL) has_avatar,(u.cover_data IS NOT NULL) has_cover FROM users u LEFT JOIN user_preferences up ON up.user_id=u.id ${where} AND u.account_status='active' ORDER BY u.created_at DESC LIMIT 60`,values);const ids=rows.map(x=>x.id);let socials=[];if(ids.length){const r=await db.query('SELECT user_id,platform,url FROM user_socials WHERE user_id=ANY($1::bigint[])',[ids]);socials=r.rows;}const by=new Map();for(const x of socials){if(!by.has(x.user_id))by.set(x.user_id,[]);by.get(x.user_id).push({platform:x.platform,url:x.url});}res.json({users:rows.map(x=>({...x,avatar_url:x.has_avatar?`/api/users/avatar/${x.id}`:null,cover_url:x.has_cover?`/api/users/cover/${x.id}`:null,socials:by.get(x.id)||[]}))});}catch(e){console.error('public list:',e.message);res.status(500).json({error:'Kullanıcılar yüklenemedi.'});}});
router.post('/password',userAuth,async(req,res)=>{try{const current=String(req.body.current_password||''),next=String(req.body.new_password||''),confirm=String(req.body.confirm_password||'');if(!current||!next)return res.status(400).json({error:'Mevcut ve yeni şifre gerekli.'});if(next.length<8||next.length>72)return res.status(400).json({error:'Yeni şifre 8-72 karakter arasında olmalı.'});if(next!==confirm)return res.status(400).json({error:'Yeni şifreler eşleşmiyor.'});const {rows}=await db.query('SELECT password_hash FROM users WHERE id=$1',[req.user.id]);if(!rows[0]||!(await bcrypt.compare(current,rows[0].password_hash)))return res.status(401).json({error:'Mevcut şifre hatalı.'});const hash=await bcrypt.hash(next,12);await db.query('UPDATE users SET password_hash=$1,updated_at=NOW() WHERE id=$2',[hash,req.user.id]);res.json({ok:true});}catch(e){console.error('password:',e.message);res.status(500).json({error:'Şifre güncellenemedi.'});}});
module.exports=router;
