const router = require('express').Router();
const db = require('../db');
function publicProduct(row) { return { id: row.id, name: row.name, description: row.description, category: row.category, price: Number(row.price), stock: row.stock, external_platform: row.external_platform || null, external_url: row.external_url || null, image_url: row.image_data ? `/api/products/${row.id}/image` : (row.image_url || null) }; }
router.get('/', async (req,res)=>{try{const {category,q}=req.query;let sql="SELECT id,name,description,category,price,stock,external_platform,external_url,image_url,image_data FROM products WHERE status='active'";const p=[];if(category&&category!=='All'){
  const platformMap={Instagram:['Instagram','instagram'],TikTok:['TikTok','tiktok'],Telegram:['Telegram','telegram'],Twitter:['Twitter','twitter','X hesab','X hesap'],Facebook:['Facebook','facebook'],Snapchat:['Snapchat','snapchat'],PSN:['PSN','PlayStation','PlayStation Network'],Steam:['Steam','steam'],Twitch:['Twitch','twitch']};
  const terms=platformMap[category];
  if(terms){const ors=terms.map((_,i)=>`name ILIKE $${p.length+i+1} OR description ILIKE $${p.length+i+1}`).join(' OR ');sql+=` AND (${ors})`;terms.forEach(t=>p.push(`%${t}%`));}
  else {sql+=` AND category=$${p.length+1}`;p.push(category)}
}if(q){sql+=` AND (name ILIKE $${p.length+1} OR description ILIKE $${p.length+2})`;p.push(`%${q}%`,`%${q}%`)}sql+=' ORDER BY created_at DESC';const {rows}=await db.query(sql,p);res.json({products:rows.map(publicProduct)});}catch(e){console.error(e);res.status(500).json({error:'Products unavailable'});}});
router.get('/:id/image',async(req,res)=>{try{const {rows}=await db.query('SELECT image_data,image_mime FROM products WHERE id=$1',[req.params.id]);if(!rows[0]?.image_data)return res.status(404).end();res.set('Content-Type',rows[0].image_mime||'application/octet-stream');res.set('Cache-Control','public, max-age=3600');res.send(rows[0].image_data);}catch(e){res.status(500).end();}});
router.get('/:id',async(req,res)=>{try{const {rows}=await db.query("SELECT id,name,description,category,price,stock,external_platform,external_url,image_url,image_data FROM products WHERE id=$1 AND status='active'",[req.params.id]);if(!rows[0])return res.status(404).json({error:'Product not found'});res.json({product:publicProduct(rows[0])});}catch(e){res.status(500).json({error:'Product unavailable'});}});
module.exports=router;
