const CART_KEY='tos_market_cart_v6',ORDER_KEY='tos_market_order_v6',SUPPORT_KEY='tos_market_support_v6';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const money=n=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:0}).format(Number(n||0));let USD_TRY_RATE=50;
async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{...(opt.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(opt.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||'İşlem başarısız');return d}
function cart(){try{return JSON.parse(localStorage.getItem(CART_KEY)||'[]')}catch{return[]}}function saveCart(c){localStorage.setItem(CART_KEY,JSON.stringify(c));updateCount()}function updateCount(){const e=$('#cartCount');if(e)e.textContent=cart().reduce((s,x)=>s+x.quantity,0)}
async function copyText(text){try{await navigator.clipboard.writeText(text);toast('Kopyalandı ✓')}catch{toast('Kopyalama başarısız')}}
function toast(m){const t=$('#toast');if(!t)return;t.textContent=m;t.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>t.classList.remove('show'),2400)}
function addToCart(p){const c=cart(),x=c.find(i=>i.productId===p.id);if(x)x.quantity=Math.min(x.quantity+1,Number(p.stock)||1);else c.push({productId:p.id,name:p.name,price:Number(p.price),stock:Number(p.stock),image_url:p.image_url||null,quantity:1});saveCart(c);toast('✓ Ürün sepete eklendi')}
function applyTheme(){const t=localStorage.getItem('tos_theme_v6')||'midnight';document.documentElement.dataset.theme=t}
async function loadSettings(){try{const d=await api('/api/settings/public');const t=d.settings.theme||'midnight';localStorage.setItem('tos_theme_v6',t);applyTheme();USD_TRY_RATE=Number(d.settings.usd_try_rate||50);if($('#usdRateLabel'))$('#usdRateLabel').textContent=`1 USD = ${USD_TRY_RATE} TL`;return d.settings}catch{return{}}}
function nav(){
  updateCount();
  $('#mobileMenu')?.addEventListener('click',()=>$('.nav-main')?.classList.toggle('open'));
  $('#supportOpen')?.addEventListener('click',openSupport);
  $('#heroSupport')?.addEventListener('click',openSupport);
  refreshAccountNav();
}
async function refreshAccountNav(){
  const link=$('#accountLink'); if(!link)return;
  try{
    const d=await api('/api/users/me');
    const u=d.user||{};
    link.href='/profile.html';
    link.classList.add('is-authenticated');
    link.innerHTML=`<span class="account-avatar-mini">${esc((u.display_name||u.nickname||'T').slice(0,1).toUpperCase())}</span><span>${esc(u.display_name||u.nickname||'Hesap')}</span>`;
    link.title='Hesabım';
  }catch{
    link.href='/auth.html';
    link.classList.remove('is-authenticated');
    link.outerHTML='<span class="guest-account-actions"><a class="account-guest-btn" href="/auth.html">Giriş</a><a class="account-guest-btn primary" href="/auth.html?mode=register">Kayıt ol</a></span>';
  }
}
async function requireUser(){
  try{return (await api('/api/users/me')).user}catch{location.replace('/auth.html?next='+encodeURIComponent(location.pathname+location.search));return null}
}
function productCard(p){return `<article class="product-card"><a href="/product.html?id=${p.id}"><div class="product-media">${p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.name)}">`:`<div class="product-mark">${esc((p.category||'T').slice(0,1))}</div>`}<span>${esc(p.category)}</span></div></a><div class="product-content"><div class="product-title"><a href="/product.html?id=${p.id}"><h3>${esc(p.name)}</h3></a><strong>${money(p.price)}<small style="display:block;color:#707b89;font:500 10px DM Sans">≈ $${(Number(p.price)/USD_TRY_RATE).toFixed(2)}</small></strong></div><p>${esc(p.description)}</p><div class="product-footer"><small>${p.stock>0?'● Stokta':'○ Tükendi'}</small><button class="button primary small" ${p.stock<=0?'disabled':''} onclick='event.preventDefault();addToCart(${JSON.stringify(p).replace(/'/g,'&#39;')})'>${p.stock>0?'Sepete ekle':'Tükendi'}</button></div></div></article>`}
async function loadProducts(){const box=$('#products');if(!box)return;const cat=$('.filter.active')?.dataset.cat||'All',q=$('#search')?.value.trim()||'';box.innerHTML='<div class="loading-card">Marketplace hazırlanıyor…</div>';try{const d=await api('/api/products?'+new URLSearchParams({category:cat,q}));box.innerHTML=d.products.length?d.products.map(productCard).join(''):'<div class="empty-card">Bu filtrede ürün yok.</div>'}catch{box.innerHTML='<div class="empty-card">Marketplace yüklenemedi.</div>'}}
async function initHome(){let timer;const urlCat=new URLSearchParams(location.search).get('category');if(urlCat){$$('.filter').forEach(x=>x.classList.toggle('active',x.dataset.cat===urlCat))}$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');loadProducts()});$('#search')?.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(loadProducts,180)});await loadSettings();loadProducts();if(new URLSearchParams(location.search).get('ai')==='1')setTimeout(()=>$('#assistant')?.classList.add('open'),250);}
function renderCart(){const box=$('#cartItems');if(!box)return;const c=cart(),total=c.reduce((s,x)=>s+x.price*x.quantity,0);$('#cartLineCount')&&(($('#cartLineCount').textContent=c.reduce((s,x)=>s+x.quantity,0)));$('#cartTotal')&&($('#cartTotal').textContent=money(total));if(!c.length){box.innerHTML='<div class="empty-card">Sepetin boş. <a href="/#market"><u>Marketplace’e dön</u></a></div>';return}box.innerHTML=c.map((x,i)=>`<div class="cart-item"><div class="cart-product"><div class="cart-thumb">${x.image_url?`<img src="${esc(x.image_url)}">`:'T'}</div><div><strong>${esc(x.name)}</strong><small>${money(x.price)} / adet</small></div></div><div class="qty"><button onclick="changeQty(${i},-1)">−</button><b>${x.quantity}</b><button onclick="changeQty(${i},1)">+</button></div><div class="cart-line"><strong>${money(x.price*x.quantity)}</strong><button onclick="removeItem(${i})">Kaldır</button></div></div>`).join('')}
function changeQty(i,d){const c=cart();if(!c[i])return;c[i].quantity=Math.max(1,Math.min(c[i].quantity+d,c[i].stock));saveCart(c);renderCart()}function removeItem(i){const c=cart();c.splice(i,1);saveCart(c);renderCart();toast('Ürün kaldırıldı')}
async function initProduct(){const id=new URLSearchParams(location.search).get('id'),box=$('#productDetail');if(!box)return;try{const d=await api('/api/products/'+id),p=d.product;document.title=p.name+' — TOS MARKET';box.innerHTML=`<div class="detail-image">${p.image_url?`<img src="${esc(p.image_url)}">`:`<div class="detail-placeholder">${esc((p.category||'T').slice(0,1))}</div>`}</div><div class="detail-copy"><span class="eyebrow">${esc(p.category)} / TOS MARKET</span><h1>${esc(p.name)}</h1><p>${esc(p.description)}</p><div class="social-copy"><span>✓ Orijinal teslim</span><span>✓ Güvenli checkout</span><span>✓ TRON / TRX</span></div><div class="detail-price">${money(p.price)} <small style="display:block;color:#7c8795;font:500 12px DM Sans">≈ $${(Number(p.price)/(USD_TRY_RATE||50)).toFixed(2)} · USD/TRY ${USD_TRY_RATE||50}</small></div><div class="detail-stock">${p.stock>0?'● Stokta':'○ Tükendi'}</div><button class="button primary huge" ${p.stock<=0?'disabled':''} onclick='addToCart(${JSON.stringify(p).replace(/'/g,'&#39;')})'>Sepete ekle →</button><div class="reviews" id="reviews"><div class="section-head"><div><span class="eyebrow">COMMUNITY</span><h2>Yorumlar</h2></div><div id="reviewAverage">—</div></div><div id="reviewList"></div><div class="panel"><h3>Satın aldıysan yorum bırak</h3><form id="reviewForm" class="review-form"><div class="stars" id="stars">${[1,2,3,4,5].map(i=>`<button type="button" class="star" data-star="${i}">★</button>`).join('')}</div><textarea class="input" id="reviewBody" rows="4" placeholder="Deneyimini paylaş..."></textarea><button class="button primary">Yorumu yayınla</button><div id="reviewError" class="hidden"></div></form></div></div></div>`;loadReviews(id)}catch{box.innerHTML='<div class="empty-card">Ürün bulunamadı.</div>'}}
async function loadReviews(id){try{const d=await api('/api/reviews/product/'+id);$('#reviewAverage').textContent=`★ ${d.average||0} / 5 · ${d.count} yorum`;$('#reviewList').innerHTML=d.reviews.length?d.reviews.map(r=>`<div class="review"><div class="review-head"><strong>${esc(r.display_name||r.nickname)}</strong><span>★ ${r.rating}</span></div><div class="review-meta">@${esc(r.nickname)} · ${new Date(r.created_at).toLocaleDateString('tr-TR')}</div><p>${esc(r.body)}</p></div>`).join(''):'<div class="empty-card">Henüz yorum yok.</div>';let rating=5;$$('#stars .star').forEach(b=>b.onclick=()=>{rating=Number(b.dataset.star);$$('#stars .star').forEach(x=>x.classList.toggle('active',Number(x.dataset.star)<=rating))});$('#reviewForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/reviews/product/'+id,{method:'POST',body:JSON.stringify({rating,body:$('#reviewBody').value})});toast('Yorum yayınlandı ✓');loadReviews(id)}catch(x){const er=$('#reviewError');er.textContent=x.message;er.classList.remove('hidden')}}}catch{}}
async function initCheckout(){const c=cart();if(!c.length){location.href='/cart.html';return}const total=c.reduce((s,x)=>s+x.price*x.quantity,0);$('#checkoutTotal').textContent=money(total);$('#createOrder').onclick=async()=>{const b=$('#createOrder');b.disabled=true;try{const me=await api('/api/users/me').catch(()=>null);const d=await api('/api/orders',{method:'POST',body:JSON.stringify({items:c.map(x=>({productId:x.productId,quantity:x.quantity})),paymentMethod:'crypto_trx',nickname:me?.user?.nickname||$('#guestNickname')?.value||'Misafir'})});localStorage.removeItem(CART_KEY);saveCart([]);localStorage.setItem(ORDER_KEY,JSON.stringify({id:d.orderId,token:d.paymentToken}));location.href=`/payment.html?id=${d.orderId}&token=${encodeURIComponent(d.paymentToken)}`}catch(e){$('#checkoutError').textContent=e.message;$('#checkoutError').classList.remove('hidden');b.disabled=false}}}
let checkoutPoll,checkoutTimer;async function initPayment(){const q=new URLSearchParams(location.search),id=q.get('id'),token=q.get('token');if(!id||!token)return;try{const d=await api('/api/crypto/create',{method:'POST',body:JSON.stringify({orderId:id,token})});$('#cryptoAmount').textContent=d.payment.expected_amount+' TRX';$('#cryptoAddress').textContent=d.address;$('#usdInfo').textContent=`${Number(d.rates.usd).toFixed(2)} USD · 1 USD = ${d.rates.usdTry} TL · 1 TRX ≈ $${Number(d.rates.trxUsd).toFixed(4)}`;$('#orderLink').href=`/order.html?id=${id}&token=${encodeURIComponent(token)}`;$('#copyAddress')?.addEventListener('click',()=>copyText(d.address));$('#copyAmount')?.addEventListener('click',()=>copyText(String(d.payment.expected_amount)));if(window.QRCode)new QRCode($('#qrcode'),{text:`tron:${d.address}?amount=${d.payment.expected_amount}`,width:205,height:205,colorDark:'#07090c',colorLight:'#ffffff'});startPayPoll(id,token,d.payment.expires_at);$('#notifyPayment').onclick=async()=>{const note=$('#paymentNote').value.trim(),tx=$('#txHash').value.trim();try{await api('/api/payments/notify',{method:'POST',body:JSON.stringify({orderId:id,token,txHash:tx,note})});$('#notifyState').textContent="✓ Ödeme bildirimin admin Control Room'a ulaştı.";toast('Ödeme bildirimi gönderildi ✓')}catch(e){toast(e.message)}}}catch(e){$('#cryptoStatus').textContent=e.message||'TRX ödeme ekranı hazırlanamadı.';$('#cryptoStatus').classList.add('bad')}}
function startPayPoll(id,token,expires){clearInterval(checkoutPoll);clearInterval(checkoutTimer);const until=Date.parse(expires),tick=()=>{const sec=Math.max(0,Math.floor((until-Date.now())/1000));$('#cryptoExpiry').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;if(!sec)clearInterval(checkoutTimer)};tick();checkoutTimer=setInterval(tick,1000);const poll=async()=>{try{const d=await api(`/api/crypto/status/${id}?token=${encodeURIComponent(token)}`),p=d.payment;if(p.status==='confirmed'){clearInterval(checkoutPoll);$('#cryptoStatus').textContent='✓ TRX ödeme doğrulandı — siparişin güncellendi.';$('#cryptoStatus').classList.add('good');$('#orderLink').classList.remove('hidden')}if(p.status==='expired'){clearInterval(checkoutPoll);$('#cryptoStatus').textContent='Süre doldu — destekten yardım iste.'}}catch{}};poll();checkoutPoll=setInterval(poll,10000)}
async function initOrder(){const q=new URLSearchParams(location.search),saved=JSON.parse(localStorage.getItem(ORDER_KEY)||'null'),id=q.get('id')||saved?.id,token=q.get('token')||saved?.token;if(!id||!token)return;$('#orderId').textContent='#'+id;const refresh=async()=>{try{const d=await api(`/api/orders/${id}?token=${encodeURIComponent(token)}`),o=d.order;$('#orderStatus').textContent={pending:'Ödeme bekleniyor',paid:'Ödeme doğrulandı',processing:'Hazırlanıyor',completed:'Teslim edildi',cancelled:'İptal edildi'}[o.status]||o.status;$('#statusIcon').textContent=['paid','processing','completed'].includes(o.status)?'✓':'•';$('#orderItems').innerHTML=d.items.map(x=>`<div class="summary-row"><span>${esc(x.product_name)} × ${x.quantity}</span><b>${money(x.unit_price*x.quantity)}</b></div>`).join('');const cp=await api(`/api/crypto/status/${id}?token=${encodeURIComponent(token)}`).then(x=>x.payment).catch(()=>null);$('#orderPayment').innerHTML=`<div class="summary-row"><span>Toplam</span><b>${money(o.total)}</b></div><div class="summary-row"><span>Ödeme</span><b>${cp?.expected_amount?cp.expected_amount+' TRX':'TRX / TRON'}</b></div>${cp?.tx_hash?`<div class="summary-row"><span>TX</span><code>${esc(cp.tx_hash)}</code></div>`:''}`;if(d.delivery?.length&&['paid','processing','completed'].includes(o.status)){$('#deliveryBox').classList.remove('hidden');$('#deliveryBox').innerHTML='<span class="eyebrow">DELIVERY</span><h3>Ürün teslimatı</h3>'+d.delivery.map(x=>`<div class="delivery"><small>${esc(x.product)}</small><pre>${esc(x.content)}</pre></div>`).join('')}}catch{}};refresh();setInterval(refresh,10000)}
function supportToken(){let t=localStorage.getItem(SUPPORT_KEY);if(!t){t=crypto.randomUUID?.()||Math.random().toString(36).slice(2)+Date.now();localStorage.setItem(SUPPORT_KEY,t)}return t}
function openSupport(){if($('#supportDrawer')){ $('#supportDrawer').classList.add('open'); loadSupport(); } else { location.href='/support.html'; }}
function initSupport(){if(!$('#supportDrawer'))return;$('#supportClose')?.addEventListener('click',()=>$('#supportDrawer').classList.remove('open'));$('#supportPageOpen')?.addEventListener('click',()=>{$('#supportDrawer').classList.add('open');loadSupport()});$('#supportAiOpen')?.addEventListener('click',()=>location.href='/?ai=1');$('#supportPhoto')?.addEventListener('change',()=>{const f=$('#supportPhoto').files[0];if(f)$('#supportPhotoName').textContent=`${f.name} · ${(f.size/1024/1024).toFixed(1)} MB`});$('#supportForm').onsubmit=async e=>{e.preventDefault();const body=$('#supportBody').value.trim(),file=$('#supportPhoto')?.files[0];if(!body&&!file){toast('Mesaj veya fotoğraf ekle');return}try{const fd=new FormData();fd.append('guestToken',supportToken());fd.append('subject',$('#supportSubject').value||'TOS MARKET Destek');fd.append('body',body);if(file)fd.append('attachment',file);await api('/api/messages/guest',{method:'POST',body:fd});$('#supportBody').value='';if($('#supportPhoto'))$('#supportPhoto').value='';if($('#supportPhotoName'))$('#supportPhotoName').textContent='Fotoğraf ekle';loadSupport();toast('Mesaj gönderildi ✓')}catch(x){toast(x.message)}};loadSupport();setInterval(loadSupport,7000)}
async function loadSupport(){const b=$('#supportMessages');if(!b)return;try{const token=supportToken(),d=await api('/api/messages/guest?token='+encodeURIComponent(token));b.innerHTML=d.messages.length?d.messages.map(m=>`<div class="chat-msg ${m.direction==='outbound'?'agent':''}"><small>${m.direction==='outbound'?'TOS MARKET':'Sen'}</small>${m.body?`<p>${esc(m.body)}</p>`:''}${m.has_attachment?`<a class="chat-attachment" href="/api/messages/attachment/${m.id}?token=${encodeURIComponent(token)}" target="_blank"><img src="/api/messages/attachment/${m.id}?token=${encodeURIComponent(token)}" alt="Ekli fotoğraf"><span>${esc(m.attachment_name||'Fotoğraf')}</span></a>`:''}</div>`).join(''):'<div class="empty-card">Merhaba 👋 Sipariş, ödeme veya ürün hakkında yazabilirsin.</div>';b.scrollTop=b.scrollHeight}catch{}}
function initAssistant(){
 const root=$('#assistant'); if(!root)return;
 const toggle=()=>root.classList.toggle('open');
 $('#assistantToggle')?.addEventListener('click',toggle);
 $('#assistantClose')?.addEventListener('click',()=>root.classList.remove('open'));
 $('#assistantLiveSupport')?.addEventListener('click',()=>{root.classList.remove('open');location.href='/support.html'});
 $$('[data-ai-q]').forEach(b=>b.addEventListener('click',()=>{const input=$('#assistantInput');if(input){input.value=b.dataset.aiQ;input.focus();$('#assistantForm')?.requestSubmit()}}));
 const send=async()=>{
  const input=$('#assistantInput'),v=input?.value.trim(); if(!v)return;
  $('#assistantMessages').insertAdjacentHTML('beforeend',`<div class="assistant-msg user"><small>Sen</small>${esc(v)}</div>`); input.value='';
  const wait=document.createElement('div'); wait.className='assistant-msg ai typing'; wait.innerHTML='<small>TOS AI</small><span class="typing-dots"><i></i><i></i><i></i></span>'; $('#assistantMessages').appendChild(wait); $('#assistantMessages').scrollTop=99999;
  try{const d=await api('/api/assistant',{method:'POST',body:JSON.stringify({message:v})});wait.classList.remove('typing');wait.innerHTML=`<small>${esc(d.assistant||'TOS AI')}</small>${esc(d.answer||'Yanıt alınamadı.')}`;}
  catch{wait.classList.remove('typing');wait.innerHTML='<small>TOS AI</small>Bağlantıda bir sorun oldu. İstersen doğrudan canlı desteğe geçebilirsin.'}
  $('#assistantMessages').scrollTop=99999;
 };
 $('#assistantForm')?.addEventListener('submit',e=>{e.preventDefault();send()});
}
function initLanguage(){
 const actions=document.querySelector('.nav-actions'); if(!actions)return;
 let wrap=$('#languagePicker')||$('.lang');
 if(!wrap){wrap=document.createElement('div');wrap.className='lang';wrap.id='languagePicker';actions.insertBefore(wrap,actions.firstChild)}
 wrap.innerHTML='<span class="lang-globe" aria-hidden="true">◉</span><select id="languageSelect" aria-label="Dil seç"><option value="tr">🇹🇷 Türkçe</option><option value="en">🇬🇧 English</option><option value="de">🇩🇪 Deutsch</option></select>';
 const select=$('#languageSelect'),saved=localStorage.getItem('tos_lang'),lang=['tr','en','de'].includes(saved)?saved:'tr';
 select.value=lang; select.onchange=()=>{localStorage.setItem('tos_lang',select.value);applyLanguage(select.value);if(document.body.dataset.page==='auth')window.__authRender?.();};
 applyLanguage(lang);
 $$('[data-lang]').forEach(b=>b.onclick=()=>{const l=b.dataset.lang;if(!['tr','en','de'].includes(l))return;localStorage.setItem('tos_lang',l);applyLanguage(l);if($('#languageSelect'))$('#languageSelect').value=l;window.__authRender?.();});
}
function applyLanguage(lang){
 const map={tr:{home:'Ana Sayfa',market:'Market',categories:'Kategoriler',why:'Neden TOS?',support:'Destek',cart:'Sepet',login:'Giriş',register:'Kayıt',live:'Canlı desteğe geç',send:'Gönder →',photo:'Fotoğraf ekle',subject:'Konu',message:'Mesajını yaz...',account:'Hesap',logout:'Çıkış',orders:'Siparişler',settings:'Ayarlar',privacy:'Gizlilik',links:'Hızlı bağlantılar',payments:'Kripto ödeme'},en:{home:'Home',market:'Marketplace',categories:'Categories',why:'Why TOS?',support:'Support',cart:'Cart',login:'Log in',register:'Sign up',live:'Live support',send:'Send →',photo:'Attach photo',subject:'Subject',message:'Write your message...',account:'Account',logout:'Log out',orders:'Orders',settings:'Settings',privacy:'Privacy',links:'Quick links',payments:'Crypto payments'},de:{home:'Startseite',market:'Marktplatz',categories:'Kategorien',why:'Warum TOS?',support:'Support',cart:'Warenkorb',login:'Anmelden',register:'Registrieren',live:'Live-Support',send:'Senden →',photo:'Foto anhängen',subject:'Betreff',message:'Nachricht schreiben...',account:'Konto',logout:'Abmelden',orders:'Bestellungen',settings:'Einstellungen',privacy:'Datenschutz',links:'Schnelllinks',payments:'Krypto-Zahlung'}}[lang]||{};
 $$('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(map[k])el.textContent=map[k]});
 document.documentElement.lang=lang;document.documentElement.dir='ltr';const sel=$('#languageSelect');if(sel)sel.value=lang;
}
function initAuth(){
 let mode=new URLSearchParams(location.search).get('mode')==='register'?'register':'login';
 const refs={login:$('#authLoginTab'),register:$('#authRegisterTab'),identifier:$('#authIdentifier'),email:$('#authEmail'),confirm:$('#authConfirm'),pass:$('#authPass'),error:$('#authError'),title:$('#authTitle'),hint:$('#authHint'),submit:$('#authSubmit'),emailField:$('#emailField'),confirmField:$('#confirmField'),label:document.querySelector('[data-auth-label]'),toggle:$('#togglePassword')};
 if(!refs.login||!refs.register||!refs.identifier||!refs.pass||!$('#authForm'))return;
 const copy={tr:{login:{title:'Giriş yap',hint:'Nickname veya e-posta adresinle hesabına güvenli şekilde giriş yap.',submit:'Giriş yap →',label:'Nickname veya e-posta',ph:'ornek_nick veya mail@example.com'},register:{title:'Hesap oluştur',hint:'Nickname, e-posta ve güçlü bir şifreyle hesabını oluştur.',submit:'Hesap oluştur →',label:'Nickname',ph:'kullanici_adi'}},en:{login:{title:'Log in',hint:'Log in securely with your nickname or email.',submit:'Log in →',label:'Nickname or email',ph:'username or mail@example.com'},register:{title:'Create account',hint:'Create your account with a nickname, email and strong password.',submit:'Create account →',label:'Nickname',ph:'username'}},de:{login:{title:'Anmelden',hint:'Melde dich sicher mit Nickname oder E-Mail an.',submit:'Anmelden →',label:'Nickname oder E-Mail',ph:'nickname oder mail@example.com'},register:{title:'Konto erstellen',hint:'Erstelle dein Konto mit Nickname, E-Mail und starkem Passwort.',submit:'Konto erstellen →',label:'Nickname',ph:'benutzername'}}};
 const render=()=>{
  const reg=mode==='register',L=localStorage.getItem('tos_lang')||'tr',c=(copy[L]||copy.tr)[reg?'register':'login'];
  refs.label.textContent=c.label;refs.title.textContent=c.title;refs.hint.textContent=c.hint;refs.submit.textContent=c.submit;refs.identifier.placeholder=c.ph;
  refs.emailField.classList.toggle('hidden',!reg);refs.confirmField.classList.toggle('hidden',!reg);refs.login.classList.toggle('active',!reg);refs.register.classList.toggle('active',reg);
  refs.identifier.name=reg?'nickname':'identifier';refs.email.required=reg;refs.confirm.required=reg;refs.pass.autocomplete=reg?'new-password':'current-password';refs.error.classList.add('hidden');
  if(!reg){refs.email.value='';refs.confirm.value='';}
 };
 window.__authRender=render;
 refs.login.addEventListener('click',()=>{mode='login';history.replaceState(null,'','/auth.html');render();refs.identifier.focus()});
 refs.register.addEventListener('click',()=>{mode='register';history.replaceState(null,'','/auth.html?mode=register');render();refs.identifier.focus()});
 refs.pass.addEventListener('input',()=>{const v=refs.pass.value,bar=$('#passwordStrengthBar'),label=$('#passwordStrength');let score=0;if(v.length>=8)score++;if(v.length>=12)score++;if(/[A-Z]/.test(v))score++;if(/[0-9]/.test(v))score++;if(/[^A-Za-z0-9]/.test(v))score++;bar.style.width=`${Math.min(100,score*20)}%`;label.textContent=v?(['Çok zayıf','Zayıf','Orta','İyi','Güçlü','Çok güçlü'][score]||''):'Güçlü şifre oluştur'});
 refs.toggle?.addEventListener('click',()=>{const visible=refs.pass.type==='text';refs.pass.type=visible?'password':'text';refs.toggle.textContent=visible?'Göster':'Gizle';refs.pass.focus()});
 $('#authForm').addEventListener('submit',async e=>{
  e.preventDefault(); if(refs.submit.disabled)return;
  const reg=mode==='register'; const identifier=refs.identifier.value.trim(); const password=refs.pass.value;
  if(!identifier||!password||(reg&&(!refs.email.value.trim()||!refs.confirm.value))){refs.error.textContent='Lütfen gerekli alanları doldur.';refs.error.classList.remove('hidden');return}
  if(reg && password!==refs.confirm.value){refs.error.textContent='Şifreler eşleşmiyor.';refs.error.classList.remove('hidden');return}
  refs.submit.disabled=true;refs.submit.classList.add('is-loading');refs.error.classList.add('hidden');
  try{
   await api('/api/users/'+(reg?'register':'login'),{method:'POST',body:JSON.stringify(reg?{nickname:identifier,email:refs.email.value.trim(),password,confirm_password:refs.confirm.value}:{identifier,password})});
   const next=new URLSearchParams(location.search).get('next');location.replace(next||'/profile.html');
  }catch(x){refs.error.textContent=x.message||'İşlem başarısız.';refs.error.classList.remove('hidden');refs.submit.disabled=false;refs.submit.classList.remove('is-loading');}
 });
 render();
}
async function initProfile(){
 const u=await requireUser(); if(!u)return;
 $('#profileName').textContent=u.display_name||u.nickname;$('#profileNick').textContent='@'+u.nickname;$('#profileEmail').textContent=u.email||'';
 $('#profileSince').textContent=new Date(u.created_at).toLocaleDateString('tr-TR');$('#avatar').textContent=(u.display_name||u.nickname||'T').slice(0,1).toUpperCase();
 $('#dataNick').textContent=u.nickname;$('#dataName').textContent=u.display_name||u.nickname;$('#dataEmail').textContent=u.email||'—';$('#profileBio').textContent=u.bio||'Profil açıklamanı Ayarlar bölümünden ekleyebilirsin.';
 $('#publicTitle').textContent='@'+u.nickname;$('#publicProfileLink').href='/user.html?nickname='+encodeURIComponent(u.nickname);
 $('#dataPrivacy').textContent=u.profile_public===false?'Gizli':'Herkese açık';
 $('#logoutUser')?.addEventListener('click',async()=>{await api('/api/users/logout',{method:'POST'}).catch(()=>{});location.replace('/');});
 try{const d=await api('/api/orders/mine/list');const box=$('#myOrders');box.innerHTML=d.orders.length?d.orders.slice(0,5).map(o=>`<a class="order-row" href="/orders.html"><span>#${o.id}</span><strong>${money(o.total)}</strong><small>${esc(o.status)}</small></a>`).join(''):'<div class="empty-card">Henüz siparişin yok.</div>';}catch{if($('#myOrders'))$('#myOrders').innerHTML='<div class="empty-card">Siparişler yüklenemedi.</div>'}
}
async function initOrders(){
 const u=await requireUser(); if(!u)return;
 const box=$('#ordersPageList');if(!box)return;
 try{const d=await api('/api/orders/mine/list');box.innerHTML=d.orders.length?d.orders.map(o=>`<a class="order-row order-row-large" href="/orders.html"><div><b>#${o.id}</b><small>${new Date(o.created_at).toLocaleString('tr-TR')}</small></div><strong>${money(o.total)}</strong><span class="status-chip">${esc(o.status)}</span></a>`).join(''):'<div class="empty-card">Henüz siparişin yok. <a href="/market.html">Market’e git →</a></div>';}catch{box.innerHTML='<div class="empty-card">Siparişler yüklenemedi.</div>'}
}
async function initSettings(){
 const u=await requireUser(); if(!u)return;
 $('#settingsDisplayName').value=u.display_name||u.nickname;$('#settingsBio').value=u.bio||'';
 try{const d=await api('/api/users/preferences');$('#profilePublic').checked=d.preferences?.profile_public!==false;}catch{$('#profilePublic').checked=true}
 $('#settingsProfileForm')?.addEventListener('submit',async e=>{e.preventDefault();try{const fd=new FormData();fd.append('display_name',$('#settingsDisplayName').value.trim());fd.append('bio',$('#settingsBio').value.trim());const f=$('#settingsAvatar')?.files?.[0];if(f)fd.append('avatar',f);await api('/api/users/profile',{method:'PUT',body:fd});toast('Profil güncellendi ✓');setTimeout(()=>location.href='/profile.html',500);}catch(x){toast(x.message)}});
 $('#passwordForm')?.addEventListener('submit',async e=>{e.preventDefault();try{await api('/api/users/password',{method:'POST',body:JSON.stringify({current_password:$('#currentPassword').value,new_password:$('#newPassword').value,confirm_password:$('#confirmPassword').value})});e.target.reset();toast('Şifre güncellendi ✓')}catch(x){toast(x.message)}});
 $('#savePrivacy')?.addEventListener('click',async()=>{try{await api('/api/users/preferences',{method:'PUT',body:JSON.stringify({profile_public:$('#profilePublic').checked})});toast('Gizlilik tercihi kaydedildi ✓')}catch(x){toast(x.message)}});
}
async function initPublicProfile(){
 const nick=new URLSearchParams(location.search).get('nickname');if(!nick)return;
 try{const d=await api('/api/users/profile/'+encodeURIComponent(nick)),p=d.profile;$('#publicName').textContent=p.display_name||p.nickname;$('#publicNick').textContent='@'+p.nickname;$('#publicBio').textContent=p.bio||'TOS MARKET kullanıcısı';$('#publicSince').textContent=new Date(p.created_at).toLocaleDateString('tr-TR');if(p.avatar_url){$('#publicAvatar').src=p.avatar_url;$('#publicAvatar').classList.remove('hidden');$('#publicAvatarText').classList.add('hidden')}}catch{const box=$('#publicProfileRoot');if(box)box.innerHTML='<div class="empty-card">Profil bulunamadı veya gizli.</div>'}
}
function boot(){
 applyTheme();initLanguage();nav();updateCount();initSupport();initAssistant();
 const p=document.body.dataset.page;
 if(p==='home')initHome();if(p==='cart')renderCart();if(p==='product')initProduct();if(p==='checkout')initCheckout();if(p==='payment')initPayment();if(p==='order')initOrder();if(p==='auth')initAuth();if(p==='profile')initProfile();if(p==='orders')initOrders();if(p==='settings')initSettings();if(p==='public-profile')initPublicProfile();
}
boot();
